export const metadata = {
  title: 'Nextjs',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }:any) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}